import json
from pathlib import Path

data = [
  ("Rice_Leaf_Roller", "Rice Leaf Roller", "Rice Leaf Roller", "Cnaphalocrocis medinalis", "Rice"),
  ("Rice_Leaf_Caterpillar", "Rice Leaf Caterpillar", "Rice Leaf Caterpillar (Green Hairy)", "Rivula atimeta", "Rice"),
  ("Paddy_Stem_Maggot", "Paddy Stem Maggot", "Paddy Stem Maggot", "Chlorops oryzae", "Rice"),
  ("Asiatic_Rice_Borer", "Asiatic Rice Borer", "Asiatic Rice Striped Borer", "Chilo suppressalis", "Rice"),
  ("Yellow_Rice_Borer", "Yellow Rice Borer", "Yellow Rice Stem Borer", "Scirpophaga incertulas", "Rice"),
  ("Rice_Gall_Midge", "Rice Gall Midge", "Rice Gall Midge", "Orseolia oryzae", "Rice"),
  ("Rice_Stemfly", "Rice Stemfly", "Rice Whorl Maggot / Stemfly", "Atherigona oryzae", "Rice"),
  ("Brown_Planthopper", "Brown Planthopper", "Brown Planthopper (BPH)", "Nilaparvata lugens", "Rice"),
  ("White_Backed_Planthopper", "White Backed Planthopper", "White-Backed Planthopper (WBPH)", "Sogatella furcifera", "Rice"),
  ("Small_Brown_Planthopper", "Small Brown Planthopper", "Small Brown Planthopper (SBPH)", "Laodelphax striatellus", "Rice"),
  ("Rice_Water_Weevil", "Rice Water Weevil", "Rice Water Weevil", "Lissorhoptrus oryzophilus", "Rice"),
  ("Rice_Leafhopper", "Rice Leafhopper", "Green Rice Leafhopper", "Nephotettix cincticeps", "Rice"),
  ("Grain_Spreader_Thrips", "Grain Spreader Thrips", "Rice Grain Spreader Thrips", "Stenchaetothrips biformis", "Rice"),
  ("Rice_Shell_Pest", "Rice Shell Pest", "Rice Hispa / Shell Pest", "Dicladispa armigera", "Rice"),
  ("Grub", "White Grub", "White Grub Larva (Chafer Beetle)", "Holotrichia spp.", "Polyphagous / Soil"),
  ("Mole_Cricket", "Mole Cricket", "Oriental Mole Cricket", "Gryllotalpa orientalis", "Polyphagous / Soil"),
  ("Wireworm", "Wireworm", "Click Beetle Wireworm", "Agriotes lineatus", "Polyphagous / Soil"),
  ("White_Margined_Moth", "White Margined Moth", "White Margined Cutworm Moth", "Agrotis spp.", "Polyphagous"),
  ("Black_Cutworm", "Black Cutworm", "Black Cutworm Caterpillar", "Agrotis ipsilon", "Vegetables / Corn"),
  ("Large_Cutworm", "Large Cutworm", "Large Yellow Underwing Cutworm", "Noctua pronuba", "Vegetables / Pulses"),
  ("Yellow_Cutworm", "Yellow Cutworm", "Turnip / Yellow Cutworm Larva", "Agrotis segetum", "Vegetables / Multi-crop"),
  ("Red_Spider", "Red Spider Mite", "Two-Spotted Red Spider Mite", "Tetranychus urticae", "Corn / Vegetables"),
  ("Corn_Borer", "Corn Borer", "Asian / European Corn Borer", "Ostrinia furnacalis", "Corn"),
  ("Army_Worm", "Armyworm", "True / Oriental Armyworm", "Mythimna separata", "Corn / Wheat"),
  ("Aphids", "Aphids", "Crop Foliage Aphids", "Aphidoidea", "Multi-crop"),
  ("Potosiabre_Vitarsis", "Flower Chafer Beetle", "White-Spotted Flower Chafer (Protaetia)", "Protaetia brevitarsis", "Corn / Fruit"),
  ("Peach_Borer", "Peach Borer", "Peach Tree Borer", "Synanthedon exitiosa", "Peach / Fruit"),
  ("English_Grain_Aphid", "English Grain Aphid", "English Grain Aphid", "Sitobion avenae", "Wheat"),
  ("Green_Bug", "Greenbug Aphid", "Wheat Greenbug Aphid", "Schizaphis graminum", "Wheat"),
  ("Bird_Cherry_Oat_Aphid", "Bird Cherry-Oat Aphid", "Bird Cherry-Oat Aphid", "Rhopalosiphum padi", "Wheat / Cereals"),
  ("Wheat_Blossom_Midge", "Wheat Blossom Midge", "Orange Wheat Blossom Midge", "Sitodiplosis mosellana", "Wheat"),
  ("Penthaleus_Major", "Redlegged Earth Mite", "Winter Grain Mite (Penthaleus major)", "Penthaleus major", "Wheat / Barley"),
  ("Longlegged_Spider_Mite", "Longlegged Spider Mite", "Brown Wheat Longlegged Spider Mite", "Petrobia latens", "Wheat"),
  ("Wheat_Phloeothrips", "Wheat Phloeothrips", "Eurasian Wheat Thrips", "Haplothrips tritici", "Wheat"),
  ("Wheat_Sawfly", "Wheat Sawfly", "Wheat Stem Sawfly", "Cephus cinctus", "Wheat"),
  ("Cerodonta_Denticornis", "Cereal Leaf Miner", "Wheat Leaf Miner Fly", "Cerodontha denticornis", "Wheat"),
  ("Beet_Fly", "Beet Fly", "Beet Leafminer Fly", "Pegomya hyoscyami", "Beet"),
  ("Flea_Beetle", "Flea Beetle", "Crucifer & Beet Flea Beetle", "Phyllotreta vittula", "Beet / Crucifers"),
  ("Cabbage_Army_Worm", "Cabbage Armyworm", "Cabbage Armyworm Moth", "Mamestra brassicae", "Beet / Brassica"),
  ("Beet_Army_Worm", "Beet Armyworm", "Beet Armyworm (Spodoptera exigua)", "Spodoptera exigua", "Beet / Vegetables"),
  ("Beet_Spot_Flies", "Beet Spot Fly", "Beet Spot Mining Fly", "Pegomya betae", "Beet"),
  ("Meadow_Moth", "Meadow Moth", "Beet Webworm Meadow Moth", "Loxostege sticticalis", "Beet / Alfalfa"),
  ("Beet_Weevil", "Beet Weevil", "Sugar Beet Root Weevil", "Bothynoderes punctiventris", "Beet"),
  ("Serica_Orientalis", "Serica Orientalis", "Brown Chafer Beetle", "Serica orientalis", "Beet / Roots"),
  ("Alfalfa_Weevil", "Alfalfa Weevil", "Alfalfa Weevil", "Hypera postica", "Alfalfa"),
  ("Flax_Budworm", "Flax Budworm", "Alfalfa / Flax Budworm", "Heliothis ononis", "Alfalfa"),
  ("Alfalfa_Plant_Bug", "Alfalfa Plant Bug", "Alfalfa Plant Bug", "Adelphocoris lineolatus", "Alfalfa"),
  ("Tarnished_Plant_Bug", "Tarnished Plant Bug", "Tarnished Plant Bug", "Lygus lineolaris", "Alfalfa / Multi-crop"),
  ("Locustoidea", "Locust / Grasshopper", "Migratory Locust / Grasshopper", "Locustoidea", "Multi-crop"),
  ("Lytta_Polita", "Polite Blister Beetle", "Alfalfa Green Blister Beetle", "Lytta polita", "Alfalfa"),
  ("Legume_Blister_Beetle", "Legume Blister Beetle", "Legume Striped Blister Beetle", "Epicauta spp.", "Alfalfa / Legumes"),
  ("Blister_Beetle", "Blister Beetle", "Ash-Gray / Striped Blister Beetle", "Epicauta vittata", "Alfalfa / Vegetables"),
  ("Therioaphis_Maculata", "Spotted Alfalfa Aphid", "Spotted Alfalfa Aphid", "Therioaphis maculata", "Alfalfa"),
  ("Odontothrips_Loti", "Legume Lotus Thrips", "Lotus & Alfalfa Thrips", "Odontothrips loti", "Alfalfa"),
  ("Thrips", "Thrips", "Crop Foliage Thrips", "Thripidae", "Multi-crop"),
  ("Alfalfa_Seed_Chalcid", "Alfalfa Seed Chalcid", "Alfalfa Seed Chalcid Wasp", "Bruchophagus roddi", "Alfalfa"),
  ("Pieris_Canidia", "Indian Cabbage White", "Asian Cabbage White Butterfly", "Pieris canidia", "Vegetables"),
  ("Apolygus_Lucorum", "Green Mirid Bug", "Small Green Plant Bug", "Apolygus lucorum", "Grape / Cotton"),
  ("Limacodidae", "Cup Moth Slug", "Slug Caterpillar (Limacodidae)", "Limacodidae", "Fruit / Grape"),
  ("Viteus_Vitifoliae", "Grape Phylloxera", "Grape Root Phylloxera Aphid", "Daktulosphaira vitifoliae", "Grape"),
  ("Colomerus_Vitis", "Grape Erineum Mite", "Grape Leaf Blister Mite", "Colomerus vitis", "Grape"),
  ("Brevipalpus_Lewisi", "Lewis Spider Mite", "Grape Flat / Bunch Mite", "Brevipalpus lewisi", "Grape / Citrus"),
  ("Oides_Decempunctata", "10-Spotted Leaf Beetle", "Grape Leaf Beetle (Oides)", "Oides decempunctata", "Grape"),
  ("Polyphagotarsonemus_Latus", "Broad Mite", "Broad Mite / Yellow Tea Mite", "Polyphagotarsonemus latus", "Multi-crop / Chilli"),
  ("Pseudococcus_Comstocki", "Comstock Mealybug", "Comstock Fruit Mealybug", "Pseudococcus comstocki", "Fruit / Grape"),
  ("Paranthrene_Regalis", "Grape Clearwing Moth", "Grape Trunk Borer Moth", "Paranthrene regalis", "Grape"),
  ("Ampelophaga", "Grapevine Sphinx Moth", "Grape Hornworm Hawk Moth", "Ampelophaga rubiginosa", "Grape"),
  ("Lycorma_Delicatula", "Spotted Lanternfly", "Spotted Lanternfly Planthopper", "Lycorma delicatula", "Grape / Fruit"),
  ("Xylotrechus", "Grape Borer Beetle", "Tiger Longicorn Grape Borer", "Xylotrechus pyrrhoderus", "Grape"),
  ("Cicadella_Viridis", "Green Leafhopper", "Green Leafhopper (Cicadella viridis)", "Cicadella viridis", "Multi-crop / Grass"),
  ("Miridae", "Mirid Bug", "Capsid / Plant Bug", "Miridae", "Multi-crop"),
  ("Trialeurodes_Vaporariorum", "Greenhouse Whitefly", "Greenhouse Whitefly", "Trialeurodes vaporariorum", "Vegetables"),
  ("Erythroneura_Apicalis", "Grape Leafhopper", "Grapevine Leafhopper", "Erythroneura apicalis", "Grape"),
  ("Papilio_Xuthus", "Asian Swallowtail", "Citrus Swallowtail Butterfly Larva", "Papilio xuthus", "Citrus"),
  ("Panonychus_Citri", "Citrus Red Mite", "Citrus Red Spider Mite", "Panonychus citri", "Citrus"),
  ("Phyllocoptruta_Oleivora", "Citrus Rust Mite", "Citrus Rust / Silver Mite", "Phyllocoptruta oleivora", "Citrus"),
  ("Icerya_Purchasi", "Cottony Cushion Scale", "Cottony Cushion Scale Insect", "Icerya purchasi", "Citrus / Acacia"),
  ("Unaspis_Yanonensis", "Arrowhead Scale", "Japanese Citrus Arrowhead Scale", "Unaspis yanonensis", "Citrus"),
  ("Ceroplastes_Rubens", "Red Wax Scale", "Pink / Red Wax Scale Insect", "Ceroplastes rubens", "Citrus / Mango"),
  ("Chrysomphalus_Aonidum", "Florida Red Scale", "Circular Black / Florida Red Scale", "Chrysomphalus aonidum", "Citrus"),
  ("Parlatoria_Ziziphi", "Black Parlatoria Scale", "Citrus Black Parlatoria Scale", "Parlatoria ziziphi", "Citrus"),
  ("Nipaecoccus_Vastalor", "Spherical Mealybug", "Spherical Lebbeck Mealybug", "Nipaecoccus viridis", "Citrus / Cotton"),
  ("Aleurocanthus_Spiniferus", "Orange Spiny Whitefly", "Citrus Spiny Whitefly", "Aleurocanthus spiniferus", "Citrus"),
  ("Bactrocera_Minax", "Chinese Citrus Fly", "Chinese Citrus Fruit Fly", "Bactrocera minax", "Citrus"),
  ("Dacus_Dorsalis", "Oriental Fruit Fly", "Oriental Fruit Fly (Bactrocera dorsalis)", "Bactrocera dorsalis", "Citrus / Mango"),
  ("Bactrocera_Tsuneonis", "Japanese Orange Fly", "Japanese Orange Gall Fruit Fly", "Bactrocera tsuneonis", "Citrus"),
  ("Prodenia_Litura", "Tobacco Cutworm", "Cotton Leafworm / Tobacco Cutworm", "Spodoptera litura", "Vegetables / Cotton"),
  ("Adristyrannus", "Citrus Stink Bug", "Citrus Green Shield Bug", "Rhynchocoris humeralis", "Citrus"),
  ("Phyllocnistis_Citrella", "Citrus Leafminer", "Citrus Serpentine Leafminer", "Phyllocnistis citrella", "Citrus"),
  ("Toxoptera_Citricidus", "Brown Citrus Aphid", "Brown Citrus Aphid (CTV Vector)", "Toxoptera citricida", "Citrus"),
  ("Toxoptera_Aurantii", "Black Citrus Aphid", "Black Citrus / Camellia Aphid", "Toxoptera aurantii", "Citrus / Tea"),
  ("Aphis_Citricola", "Spirea Aphid", "Green Citrus / Spirea Aphid", "Aphis spiraecola", "Citrus / Apple"),
  ("Scirtothrips_Dorsalis", "Chilli Thrips", "Yellow Tea / Chilli Thrips", "Scirtothrips dorsalis", "Chilli / Citrus"),
  ("Dasineura_Sp", "Mango Gall Midge", "Mango Leaf Gall Midge", "Dasineura spp.", "Mango"),
  ("Lawana_Imitata", "Flatid Planthopper", "White Moth Flatid Planthopper", "Lawana imitata", "Mango / Citrus"),
  ("Salurnis_Marginella", "Green Flatid Planthopper", "Green Flatid Planthopper", "Salurnis marginella", "Mango / Tea"),
  ("Deporaus_Marginatus", "Mango Leaf-Cutting Weevil", "Mango Leaf-Cutting Weevil", "Deporaus marginatus", "Mango"),
  ("Chlumetia_Transversa", "Mango Shoot Borer", "Mango Shoot Borer Caterpillar", "Chlumetia transversa", "Mango"),
  ("Mango_Flat_Beak_Leafhopper", "Mango Flat Beak Leafhopper", "Mango Flat Beak Leafhopper", "Idioscopus nitidulus", "Mango"),
  ("Rhytidodera_Bowringii", "Mango Stem Borer Longhorn", "Mango Branch / Stem Longhorn Beetle", "Rhytidodera bowringii", "Mango"),
  ("Sternochetus_Frigidus", "Mango Pulp Weevil", "Mango Pulp / Seed Weevil", "Sternochetus frigidus", "Mango"),
  ("Cicadellidae", "Leafhopper", "Sharpshooter / Foliage Leafhopper", "Cicadellidae spp.", "Multi-crop")
]

ts_lines = ["export const IP102_PEST_TAXONOMY: PestTaxonomyItem[] = ["]
for cname, pname, dname, sname, crop in data:
    ts_lines.append(f"  {{ className: '{cname}', pestName: '{pname}', displayName: '{dname}', scientificName: '{sname}', crop: '{crop}' }},")
ts_lines.append("];\n")

Path("scripts/ip102_taxonomy.ts").write_text("\n".join(ts_lines), encoding="utf-8")
print(f"Successfully generated scripts/ip102_taxonomy.ts with {len(data)} items!")
